###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Check",
    "sender": "Ido",
    "content": "Hello World"
}


###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Ido

###

GET http://localhost:3000/posts/678e1514b38b3ed3f8dc40b9

###

PUT http://localhost:3000/posts/678e1514b38b3ed3f8dc40b9
Content-Type: application/json

{
    "title": "Ohad",
    "sender": "Ohad",
    "content": "Change"
}


###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "content": "Check",
    "post": "678e1514b38b3ed3f8dc40b9"
}


###

GET http://localhost:3000/comments


###

GET http://localhost:3000/comments/678e1987137cba3dc1dcaf15


###

PUT http://localhost:3000/comments/678e1987137cba3dc1dcaf15
Content-Type: application/json

{
    "content": "Change",
    "post": "678e1514b38b3ed3f8dc40b9",
}

###

DELETE http://localhost:3000/comments/678e1987137cba3dc1dcaf15

###

DELETE http://localhost:3000/posts/678e1514b38b3ed3f8dc40b9
